### ISSUE TITLE
marquee-background doesn't show up

### ISSUE THREAD

**Issue by Bang1338** [milkywaydotmoe/milkyweb#5]
`marquee-background` (aka the rainbow text scroller) doesn't work
possible cause: `ReferenceError: updateMarquee is not defined` in `marquee.js`

fix: i'm still trying to figuring out

**Comment by milkywaydotmoe** [comment]
Honestly i have no idea.

**Comment by Bang1338** [comment]
> Honestly i have no idea.

when it that happened?

**Comment by milkywaydotmoe** [comment]
Nevermind. Fixed on latest update. I forgot to declare one of the functions.

**Comment by Bang1338** [comment]
Well met!
